const campeonatosDisponiveis = [
  {
    id: 1,
    nome: "Campeonato Brasileiro",
    jogo: "Counter Strike: Global Offensive",
    dataInicio: "11/04/2022",
    dataFim: "16/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 10,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 2,
    nome: "Campeonato Centro-Oeste",
    jogo: "League of legends",
    dataInicio: "11/04/2022",
    dataFim: "16/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 15,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 3,
    nome: "Campeonato São Paulo",
    jogo: "Valorant",
    dataInicio: "11/04/2022",
    dataFim: "16/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 05,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 4,
    nome: "Campeonato Brasileiro",
    jogo: "Street Figther",
    dataInicio: "11/04/2022",
    dataFim: "16/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 10,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 5,
    nome: "Campeonato São Paulo",
    jogo: "Counter Strike: Global Offensive",
    dataInicio: "20/04/2022",
    dataFim: "30/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 02,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 6,
    nome: "Campeonato Centro-Oeste",
    jogo: "Valorant",
    dataInicio: "20/04/2022",
    dataFim: "30/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 05,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 7,
    nome: "Campeonato Centro-Oeste",
    jogo: "Street Figther",
    dataInicio: "20/04/2022",
    dataFim: "30/04/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 05,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
  {
    id: 8,
    nome: "Campeonato Rio de Janeiro",
    jogo: "Counter Strike: Global Offensive",
    dataInicio: "22/04/2022",
    dataFim: "02/05/2022",
    quantidadeTimes: 20,
    quantidadeTimesInscritos: 01,
    formatoCampeonato: "default",
    linkCampeonato: "#",
  },
];

module.exports = campeonatosDisponiveis;
